test_style:
  image: python:3.6
  script:
  - pip3 install flake8
  - flake8 . --exclude=venv --max-line-length 120  # imo 120 is way too much

test_code_py3:
  image: python:3.6
  script:
  - pip3 install -r requirements.txt
  - pip3 install pytest
  - pytest .

test_code_py2:
  image: python:2.7
  script:
  - pip install -r requirements.txt
  - pip install pytest
  - pytest .

test_e2e:
  image: python:3.6
  script:
  - pip3 install -r requirements.txt
  - pip3 install pytest
  - pytest tests/e2etest_mwdblib.py
