from .object import MWDBObject
from .config import MWDBConfig
from datetime import datetime
from typing import Optional


class MWDBBlob(MWDBObject):
    URL_TYPE: str = ...
    TYPE: str = ...
    @property
    def blob_name(self) -> str: ...
    @property
    def blob_size(self) -> int: ...
    @property
    def blob_type(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def size(self) -> int: ...
    @property
    def type(self) -> str: ...
    @property
    def content(self) -> str: ...
    @property
    def config(self) -> Optional[MWDBConfig]: ...
    @property
    def last_seen(self) -> datetime: ...
