from .object import MWDBElement
from typing import Any
from datetime import datetime


class MWDBComment(MWDBElement):
    parent: Any = ...
    def __init__(self, api: Any, data: Any, parent: Any) -> None: ...
    @property
    def id(self) -> int: ...
    @property
    def author(self) -> str: ...
    @property
    def timestamp(self) -> datetime: ...
    @property
    def comment(self) -> str: ...
    def delete(self) -> None: ...
