from .object import MWDBObject
from typing import Dict, Any


class MWDBConfig(MWDBObject):
    URL_TYPE: str = ...
    TYPE: str = ...
    @property
    def family(self) -> str: ...
    @property
    def type(self) -> str: ...
    @property
    def config_dict(self) -> Dict[str, Any]: ...
    @property
    def config(self) -> Dict[str, Any]: ...
    @property
    def content(self) -> bytes: ...
    @property
    def cfg(self) -> Dict[str, Any]: ...
