from typing import Any, Optional, List
from .methods import MWDBMethods
from .remote import MWDBRemote

class MWDB(MWDBMethods):
    api: Any = ...
    def __init__(self, api: Optional[Any] = ..., **api_options: Any) -> None: ...
    def login(self, username: Optional[Any] = ..., password: Optional[Any] = ..., warn: bool = ...) -> None: ...
    def logout(self) -> None: ...
    def list_remotes(self) -> List[str]: ...
    def remote(self, remote_name: str) -> MWDBRemote: ...


Malwarecage = MWDB
