from .object import MWDBElement
from typing import Any, Dict
from .api import MalwarecageAPI
from datetime import datetime


class MWDBShareReason:
    api: MalwarecageAPI = ...
    def __init__(self, api: MalwarecageAPI, share_data: Dict[str, str]) -> None: ...
    @property
    def what(self) -> Dict[str, str]: ...
    @property
    def why(self) -> str: ...
    @property
    def who(self) -> str: ...


class MWDBShare(MWDBElement):
    parent: Any = ...
    def __init__(self, api: MalwarecageAPI, data: Dict[str, Any], parent: Any) -> None: ...
    @property
    def timestamp(self) -> datetime: ...
    @property
    def group(self) -> str: ...
    @property
    def reason(self) -> MWDBShareReason: ...


MalwarecageShareReason = MWDBShareReason
MalwarecageShare = MWDBShare
