name: Lint and test mwdblib

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black==21.10b0 flake8==3.8.3 isort==5.10.1 mypy==0.910 pytest
        pip install types-requests
        pip install .
    - run: isort --check mwdblib/
    - run: black --check mwdblib/
    - run: flake8 mwdblib/
    - run: mypy mwdblib/

    - name: Test with pytest
      run: |
        pytest
