name: Lint and test mwdblib

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: CERT-Polska/lint-python-action@v2
        with:
          install-requirements: false
          extra-requirements: "types-requests keyring"
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.10, 3.11, 3.12]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: pip install .
      - run: pip install pytest==5.4.1
      - name: Test with pytest
        run: pytest
